# Site settings
title: Diurnalis
email: pm@aliakbars.id
description: "Personal notes"
baseurl: ""
url: "http://aliakbars.github.io"
twitter_username: aliakbars
github_username:  aliakbars

# Build settings
markdown: kramdown
permalink: pretty

theme: jekyll-theme-cayman
